services:
  server:
    env_file:
      - ./.env
    volumes:
      - ./.env:/usr/mount.d/.env
    build:
      context: ./server/src
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    container_name: area-server
    networks:
      - web

  database:
    env_file:
      - ./.env
    image: postgres
    container_name: area-database
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./server/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./server/database/time.sql:/docker-entrypoint-initdb.d/time.sql
    networks:
      - web
    
  service-discord:
    env_file:
      - ./server/services/discord/.env
      - ./.env
    volumes:
      - ./server/services/discord/.env:/usr/mount.d/.env
      - ./.env:/usr/mount.d/.env1
    container_name: area-service-discord
    build:
      context: ./server/services/discord
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.discord.rule=PathPrefix(`/service/discord/`)"
      - "traefik.http.services.discord.loadbalancer.server.port=80"
      - "traefik.http.routers.discord.middlewares=stripprefix-service-discord"
      - "traefik.http.middlewares.stripprefix-service-discord.stripprefix.prefixes=/service/discord"
    environment:
      - DB_HOST=database
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    networks:
      - web
    
  service-time:
    env_file:
      - ./.env
    container_name: area-service-time
    build:
      context: ./server/services/time
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time.rule=PathPrefix(`/service/time/`)"
      - "traefik.http.services.time.loadbalancer.server.port=80"
      - "traefik.http.routers.time.middlewares=stripprefix-service-time"
      - "traefik.http.middlewares.stripprefix-service-time.stripprefix.prefixes=/service/time"
    environment:
      - DB_HOST=database
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
    networks:
      - web

  reverse-proxy:
    image: traefik:v${TRAEFIK_VERSION}
    container_name: area-traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:${TRAEFIK_PORT}"
    ports:
      - "${TRAEFIK_PORT}:${TRAEFIK_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web

  client_web:
    env_file:
      - ./.env
    container_name: area-client-web
    build:
      context: ./web
    ports:
      - ${WEB_PORT}:80
    networks:
      - web

networks:
  web:
    external: false
