services:
  backend:
    env_file:
      - .env
    build:
      context: ./src
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=area_database
    container_name: area-backend

  database:
    env_file:
      - .env
    image: postgres
    container_name: area-database
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=area_database
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
